name: deploy-site
on: 
  push:
    branches:
      - master
      - feature/google_login
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      # Checkout Branch
      - uses: actions/checkout@v2
      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # set .env file
      - name: Set Env REACT_APP_ALLOW_GOOGLE_ID
        run: echo "REACT_APP_ALLOW_GOOGLE_ID=${{ secrets.REACT_APP_ALLOW_GOOGLE_ID }}" > .env
      # set .env file
      - name: Set Env REACT_APP_GOOGLE_CLIENT_ID
        run: echo "REACT_APP_GOOGLE_CLIENT_ID={{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" >> .env
      # npm install
      - name: npm install
        run: npm install
      # build ReactApp
      - name: React Build
        run: npm run build
      # Check Build Directory
      - name: Listup-directory
        run: ls -la build
      # Deploy FTP Server
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0 
        env:
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: build
          REMOTE_DIR: Animel
          ARGS: --verbose --parallel=100
      # Notice Slack
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}